environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\appveyor\\run_with_env.cmd"

  ANACONDA_TOKEN:
    secure: OjKnjIfwmCT54OA/MYq9mjSxVLN2elITvKcY2ASm5cGT0tAUMOvbRGn5VdtqQnq+

  matrix:
    - PYTHON: "C:\\Python35_64"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      CONDA_PY: "35"
      CONDA_NPY: "18"
      QTDIR: "C:\\Qt\\5.6\\msvc2015_64"
      QDOWNLOAD: "http://download.qt.io/development_releases/qt/5.6/5.6.0-beta/qt-opensource-windows-x86-msvc2015_64-5.6.0-beta.exe"
      QINSTALLER: "qt-opensource-windows-x86-msvc2015_64-5.6.0-beta.exe"
      platform: x64

    - PYTHON: "C:\\Python35_32"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "32"
      CONDA_PY: "35"
      CONDA_NPY: "18"
      QTDIR: "C:\\Qt\\5.6\\msvc2015"
      QDOWNLOAD: "http://download.qt.io/development_releases/qt/5.6/5.6.0-beta/qt-opensource-windows-x86-msvc2015-5.6.0-beta.exe"
      QINSTALLER: "qt-opensource-windows-x86-msvc2015-5.6.0-beta.exe"
      platform: x86

install:
  # this installs the appropriate Miniconda (Py2/Py3, 32/64 bit),
  # as well as pip, conda-build, and the binstar CLI
  - powershell .\\appveyor\\install.ps1
  - curl -kLO %QDOWNLOAD%
  - 7z x %QINSTALLER% > nul
  - move $OUTDIR "C:\\Qt\\5.6.0"
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  # Add qt to path
  - "set PATH=%QTDIR%\\bin;%PATH%"
  - "echo %PATH%"
  - choco install -y vcredist2015
  - "conda config --set always_yes yes --set changeps1 no"
  - "conda install conda-build"
  - "conda install anaconda-client"

build_script:
  - ".\\appveyor\\build.cmd"
  # Move the conda package into the current directory, to register it
  # as an "artifact" for Appveyor. cmd.exe does't have good globbing, so
  # we'll use a simple python script.
  - python appveyor\move_conda_pkg.py sip
  - python appveyor\move_conda_pkg.py pyqt5

artifacts:
  # Archive the generated conda package in the ci.appveyor.com build report.
  - path: '*.tar.bz2'

on_success:
  # Upload built binaries to binstar.org. The globbing and handling of the
  # exit-status code is tricky in cmd.exe or powershell, so we're just using
  # a python script.
  - python appveyor\anaconda_push.py
