package:
  name: sip
  version: 4.18

source:
  fn:   sip-4.18.dev1603251537.zip                                                                             [win]
  url:  https://www.riverbankcomputing.com/static/Downloads/sip4/sip-4.18.dev1603251537.zip      [win]
  sha1: a6ef8e3fd7616c8e238934d66a4243d068bcf2e5                                                 [win]

requirements:
  build:
    - python
    - python.app   [osx]

  run:
    - python

test:
  imports:
    - sip

  files:
    - test

  commands:
    - sip -c test test/word.sip

about:
  home: http://www.riverbankcomputing.com/software/sip/intro
  license: GPL3
