package:
  name: pyqt5
  version: 5.6

source:
  fn:   PyQt5_gpl-5.6.dev1604041221.zip                                                                               [win]
  url:  https://www.riverbankcomputing.com/static/Downloads/PyQt5/PyQt5_gpl-5.6.dev1604041221.zip       [win]
  sha1: c628301b4da786f0b74b92f749170b0ab6d3e677                                                     [win]

  patches:
    - configure.patch       [osx]

requirements:
  build:
    - python
    - sip     >=4.18

  run:
    - python
    - sip     >=4.18

test:
  imports:
    - PyQt5.QtCore

about:
  home: http://www.riverbankcomputing.co.uk/software/pyqt
  license: GPL

