package:
  name: pyqt5
  version: 5.6

source:
  fn:   PyQt5_gpl-5.6.dev1604021410.zip                                                                               [win]
  url:  https://www.riverbankcomputing.com/static/Downloads/PyQt5/PyQt5_gpl-5.6.dev1604021410.zip       [win]
  sha1: a4820e26d41a69284d58f0d28df7ae8713973d26                                                        [win]

  patches:
    - configure.patch       [osx]

requirements:
  build:
    - python
    - sip     >=4.18

  run:
    - python
    - sip     >=4.18

test:
  imports:
    - PyQt5.QtCore

about:
  home: http://www.riverbankcomputing.co.uk/software/pyqt
  license: GPL

